# Generated by Django 2.2.12 on 2022-06-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choises',
            new_name='choise',
        ),
    ]
