# Generated by Django 2.2.12 on 2022-06-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220625_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choise',
            new_name='choice',
        ),
    ]
